
// Experiment file Coco 

// This says: "begin with the intro, then follow it with real sentences evenly
// shuffled with npi sentences, with each sentece separated by the "sep"
// item (a 1 second pause).

//document.querySelector('input').setAttribute('autofocus', 'autofocus');

var shuffleSequence = seq("consent", "demo","welcome", "BookCover", 
                           startsWith("coco"),"debrief","exit"
                         );
var showProgressBar = false;
//var counterOverride = 2;
                  
var fullStory = ['My sister is the world\'s greatest detective! She has solved many mysteries like the case of the bubble gum bandit and the nap time nuisance.', 'But this case, the case of the turtle snatcher is her greatest accomplishment.', 'Let\'s start from the beginning: On the third day of the third month of the third grade, my sister was handing out birthday invitations to all the kids in room 113.', 'Her name is Tulena Clarissa Warren the first, but our Mom and everybody else call her Tully.', 'Our mom says she is a fashionista, which means that she really, really likes clothes.', 'That day, she wore her furry pink vest over a green rainbow T-shirt with a jean skirt and blue leggings dotted with pink circles.', 'She had just come back to class after first recess.', 'Kids were still getting drinks from the drinking fountain and grabbing their English books out of their lockers.', 'Tully handed the invitations to her four best friends: Lyra, Caleb, Rocket, and Alex.', 'The five of them were the members of the Gumshoe gang.', 'A gumshoe is a detective who cracks cases.', 'Mr Sleuth, the school secretary, gave them that nickname, since they solve all of the mysteries that occur at Watson Elementary.', 'Tully pulled the last invitation from her pocket and gave it to Lyra.', '\"Oh, thank you!\" Lyra said.', '\"When is the party?\" Caleb asked, squinting at the invitation.', 'These letters are so squiggly I can\'t even read it!\" \"It\'s called cursive, silly.', 'And the party is this Sunday.', 'That\'s five days away\".', '\"I\'ll ask my mom as soon as I get home,\" Alex said, pushing on his glasses.', '\"Will there be anything related to aliens there?\" Rocket asked.', '\"Like an alien spaceship pi\u00F1ata? Or a green Planet Moog cake?\"','Rocket\'s real name was Ronald Gonzaga, but everybody called him Rocket because he could beat almost anybody in a race.', '\"No, Rocket.', 'This is my birthday, not yours\".', 'Tully said.', 'Even though Tully was planning an elegant dress-up party, she wanted to invite all the boys in the class too.','Just then the teacher, Miss Flores, clapped her hands.', '\"Back to your seats, class!\" It\'s time for language arts.', 'Miss Flores pointed to the whiteboard, which had a bunch of sentences on it.', '\"This morning, we are going to talk about good punctuation\".', 'Caleb poked Tully\'s arm.', '\"That means not being late\".', 'He grinned for sounding so smart.', '\"No,\" Lyra whispered.', '\"That\'s punctual, not punctuation.', 'Punctuation is periods and commas and stuff\".', 'Caleb\'s face got red from embarrassment.', '\"I knew that, I was just testing you!\" \"Alright class, we are going to read each sentence together, and then you can help me figure out what important parts of the sentence are missing, okay?\" \"Look at the first sentence: My cat is so lazy I have to hire other cats to take naps for her\".', 'Everybody howled with laughter.', 'Rocket fell right out of his seat.', '\"Can we write one for a parakeet?\" Carys asked.', '\"And my box turtle!\" Emily said, bouncing in her chair.', '\"Like, ‘My turtle is so slow he walks backwards\'\".', 'Miss Flores held up her hands.', '\"Emily that was fantastic.', 'Yes, let\'s write one for each of our pets.', 'But first, we need to do the assignment.', 'Deal?\" \"Deal!\" everybody yelled.', 'The next day, Tully was getting ready for school.', 'She dug through her entire closet searching for the right outfit to wear.', '\"Oh, dear!\" Mom said as she tried to come into Tully\'s room.', 'She peeked around the clothes mountain.', '\"What on Earth is going on in here?\" \"Just getting dressed!\" Tully said.', 'She climbed over her clothes, slid down the other side to the floor, and showed Mom her plain white T-shirt and brown corduroy pants.', 'She gave Mom a hug as Mom handed Tully her lunch box and a breakfast bar.','Tully ran outside to get on the bus and headed to school.', 'At school, Mrs Holmes was standing at the front door greeting students as they came in.', 'On Wednesday mornings and Friday afternoons, students went upstairs to the library.', 'The library was a huge room with thousands of books stacked on rows of shelves that went all the way up to the ceiling.', 'The librarian, Mr Hornswoggle, had to use a stepladder to reach the highest books.', 'Mr Hornswoggle really loved books.', 'He also loved animals.', 'Even though the library was technically not a classroom, he had more class pets than any of the other teachers.', 'As soon as they got to the library, the Gumshoe gang ran over to say hello.', 'The pets were lined up in glass cages beneath the windows.', 'There was a black rat snake named Zake, a white fluffy hamster named Howard, and a gigantic tarantula called Fluffy.', 'Let me tell you, even though he was hairy, that spider was definitely not fluffy.', 'There was also Coco the turtle.', 'Sometimes when he opened his mouth, he looked like he was grinning at you.', 'Mr Hornswoggle rang a little bell from his desk.', 'That meant it was time for Tully\'s class to pick out their favorite books for the week and check them out.', 'Tully really wanted a pet for her birthday.', 'She had made a list for Mom, but she wasn\'t sure whether to ask for a parrot or a St Bernard dog or a python or a ferret, so she used the Dewey Decimal system to find the animal section to do some research.', 'Mr Hornswoggle found her as she was flipping through a book of exotic pets like monkeys and jungle cats.', 'He coughed and patted around his vest pockets for his glasses.', 'The only problem was they were on his face already.', 'Tully pointed to her eyes and cleared her throat.', '\"Oooh, of course.', 'Thank you dear.', 'Tully, I wanted to speak with you.', 'I am leaving after lunch for a meeting and I won\'t be back until tomorrow.', 'I usually take care of the animals myself on Wednesdays, but I was hoping you might be able to fill in for me today, maybe after school?\" Tully\'s heart did a little leap.', '\"Of course, Mr Hornswoggle!\" Tully said.', '\"I\'ll just phone my mother from the office.', 'I\'m sure she won\'t mind\".', 'Mom didn\'t care, of course.', 'She is great like that! After school, Tully hugged all of her friends goodbye, slung her backpack over her shoulder, and made her way to the library.', 'Right away, she noticed Howard the hamster\'s lid was ajar.', 'Howard was running in his metal wheel.', 'He gave Tully a look, twitched his nose, and kept right on running.', 'Tully fixed his lid, then got the plastic container full of crickets to feed to Fluffy the tarantula.', 'And that\'s when Tully, the great detective, noticed the aquarium\'s lid was ajar too.', 'Interesting! Coco always spends his time swimming around his aquarium or laying on a rock under his UV sun lamp, which Mr Hornswoggle called \"basking\".', 'Tully searched the whole enclosure, but he wasn\'t basking or blending in anywhere.', 'Coco was gone! Tully\'s heart was beating like a million pounding horses were stuck inside her.', '\"Where in the world was Coco? Could he have climbed out of his glass cage?\" Tully thought.', 'She got down on the floor and crawled around, checking under the tables and the bookcases.', 'But all Tully saw were little white hairs, which stuck to the knees of her pants.', 'Hmmm, what could those be from? But first things first, why would someone steal Coco? Since Tully was an amazing detective, she knew that the tiny details are the key to solving a case.', 'If Coco was stolen, then the library was definitely a crime scene.', 'Tully quickly pulled out her notebook out of her backpack.', 'She was in charge of writing down all of the notes for the Gumshoe gang, which was usually stuff like suspects, dues, motives, and alibis.', 'She examined the scene.', 'She wrote down that both Howard and Coco\'s lids had been removed.', 'She walked all along the row of cages, looking for something out of place.', 'Aha! At the end of the table next to Zake\'s cage was a paper towel.', 'Sitting on top of the paper towel was a large hunk of cheddar cheese with a single bite taken out.', 'A bite so perfect, she could see all of the teeth marks.', 'Tully carefully lifted the hunk of cheese and placed it in her backpack.', 'She quickly finished giving food and water to Howard and Zake and glanced at the clock.', 'Alex would be in extended day right now, so Tully had 20 minutes to go see him and tell him about Coco!', 'Extended day was held in the gym after school.', 'Alex was at the crafts table, drawing some kind of weird science experiment with Javier.', 'Tully slipped into the seat opposite Alex.', '\"Coco\'s gone,\" Tully said.', 'Alex looked up and squinted at her.', '\"What are you doing here, Tully?\" \"Never mind that.', 'Coco\'s been turtle-napped!\" \"What? The turtle\'s taking a nap?\" \"No! Like kidnapped! Coco\'s gone!\" Javier gasped.', '\"That\'s terrible!\" \"I know,\" Tully said and then quickly explained what she\'d found.', '\"We need to tell Mr Hornswoggle,\" Alex said, putting down his marker.', '\"He won\'t be back at school until tomorrow.', 'I was hoping we could figure out something today,\" Tully said.', '\"What if he climbed out of his cage?\" Alex asked.', 'Javier shook his head.', '\"Turtles can\'t climb.', 'Especially aquatic turtles\".', 'Tully stared at Javier.', '\"Hey, you know a bunch about animals, right?\" Javier shrugged.', '\"Some.', 'I guess.', 'My parents own the pet shop Claws and Paws down at the Centerville mall\".', '\"That\'s right! Then you can help us,\" Tully said as she whipped out her notebook.', '\"What do you mean by aquatic turtle?\" \"Aquatic turtles need to be in water most of the time, that\'s why their feet are webbed.', 'Land turtles like to swim sometimes, but they spend a lot of time, well, on land\".', '\"What kind of aquatic turtle is Coco?\" Tully asked.', 'Javier shrugged again.', '\"I don\'t know.', 'Some kind of map turtle.', 'The pattern of white, black, and green lines and circles all over his carapace looks like a map, but there are lots of different kinds of map turtles.', 'And we don\'t have any as pretty as Coco at the pet store\".', 'Tully stopped him and wrinkled her nose.', '\"Wait, what is a carapace?\" \"His shell,\" Javier explained.', '\"Oh, why didn\'t you say that silly!\"', 'Tully laughed and all of them continued going over Tully\'s notes.', 'Suddenly, the most popular girl in class, Megan, pranced over to see what the Gumshoe gang was up to.', '\"What\'s all the excitement over here?\" Alex was about to tell her, but Tully narrowed her eyes at him.', 'Just then, Tully noticed something about Megan\'s black V-neck sweater.', 'She reached over and plucked off a short white hair.', '\"Ewwwww! What is that?\" Megan squealed.', 'Tully held it between her fingertips with one hand and picked up one of the white hairs stuck to the knees of her own pants.', 'She put them side by side.', '\"Voila, a match!\" Tully exclaimed.', 'Megan made a face like she\'d just had a bite of a sour lemon.','\"Megan, do you know whose hairs these are?\" Tully asked, obviously knowing the answer already.', '\"I don\'t know\u2026 they could be from anywhere!\" Megan replied.', '\"But they aren\'t from anywhere.', 'These hairs prove you were at the scene of the crime!\" Megan looked at Tully and then at the two white hairs.', '\"What are you even talking about?\" Megan\'s face looked panicky.', '\"These hairs prove you were at the scene of the crime.', 'One hair is from your sweater, and the other came from the library carpet.', 'And they\'re both from Howard the hamster!\" Tully said with a grin knowing that she was the greatest detective in Watson Elementary.', 'Javier\'s mouth fell open.', '\"Wow.', 'That\'s amazing\".', 'Megan blew a puff of air out of her cheeks.', '\"Okay, fine.', 'I snuck into the library during lunch because I knew Mr Hornswoggle wasn\'t in there to catch me.', 'Are you happy now?\" Tully crossed her arms.', '\"I am very happy, thank you very much.', 'Now hand over Coco\".', 'Megan glared at her.', '\"Wait, what are you talking about now?\"', '\"You just said that you snuck into the library to steal Coco!\" Alex said.', '\"No, no, no.', 'I snuck into the library to play with Howard, not to steal Coco!\" Megan sighed and looked around like she was about to get into big trouble if anyone overheard.', '\"My parents don\'t let me have any pets.', 'So once in a while I like to play with that silly hamster.', 'Okay? You win\".', 'Only the Gumshoe gang didn\'t win anything at all.', 'Coco was still turtle-napped.', '\"Was Coco in his aquarium when you were there during lunch?\" Alex asked.', '\"Yes, he was lying on that rock like he was a rock himself.', 'Honestly, what do you people see in that thing? Anyways, good luck with the turtle hunt\".', 'Megan turned and skipped off to play with her other friends.', 'And just like that, one suspect was down already, and Tully was no closer to solving the mystery of the turtle snatcher.', 'The next morning, Mr Hornswoggle came into the classroom just as they were moving over to the learning rug to play the Favorite Things game.', '\"May I speak with Tully for a moment?\" Mr Hornswoggle asked Miss Flores.', 'Tully quickly whispered the situation in Miss Flores\' ear, and she gave the Gumshoe gang a hall pass.', '\"Make it quick!\" They stepped out into the hall with Mr Hornswoggle.', 'Tully told him all about yesterday.', '\"Oh, dear,\" he said.', '\"This is very distressing\".', '\"We\'re going to get Coco back,\" Tully said.', '\"We are on the case, sir,\" Alex said.', 'Mr Hornswoggle pulled a handkerchief out of his pocket and patted his forehead.', '\"I very much hope so.', 'You see, Coco is gravid, and so we must make sure she returns to the nest in time\".', 'They all had no idea what he was talking about.', 'Lyra and Tully raised their eyebrows at each other.', '\"Huh?\" Alex said.', '\"Oh, sorry.', 'Gravid means pregnant! Coco is going to be a mother,\" Mr Hornswoggle explained.', '\"What?\" Tully nearly shouted.', '\"But Coco is a boy!\" Mr Hornswoggle laughed.', '\"Everyone says \‘he\' and so I don\'t correct them, but he is very much a she\".', '\"But, but, who-\" Lyra sputtered, covering her mouth with her hands.', 'Then she whispered, \"Who is Coco\'s husband?\" Mr Hornswoggle chuckled again.', '\"It is a strange fact about turtles, but some females can lay a clutch of eggs years after mating.', 'Coco used to have a mate, but he passed away quite a while ago\".', '\"Holy moly,\" Lyra said.', '\"Wow, Mr Hornswoggle!\" Caleb said.', '\"You are like an empty well of knowledge!\" \"He means that as a compliment,\" said Alex.', 'Tully quickly pulled out her notebook from her back pocket.', '\"Mr Hornswoggle, do you have any idea who would want to snatch a turtle?\" \"Hmmm, not really!\" he said.', 'He took off his glasses and started polishing them with his vest.', '\"Coco is a Cagle\'s Map turtle, which is pretty rare.', 'They are only found in a certain river in Texas.', 'And she is a very beautiful turtle with all of those green circles and spirals on her carapace\".', '\"Carapace! That means shell!\" Tully interjected.', '\"Very good,\" Mr Hornswoggle said.', '\"Would someone want Coco because she\'s rare?\" Mr Hornswoggle nodded.', '\"Possibly.', 'An adult Cagle\'s map turtle could easily sell for more than two hundred dollars, depending on the market.', 'Hatchlings could go for well over one hundred dollars each\".', '\"Wow, that\'s a lot of cold, hard cash.', 'I could probably buy a whole pony with that kind of money,\" Tully said.','Mr Hornswoggle got a phone call and quickly returned to the library.', 'The Gumshoe gang huddled close and tried to make a plan.', '\"How about asking Javier? He knows a lot about animals, maybe he would know something!\" Tully said.', 'It was perfect timing because it was time for recess.', 'They went outside and found Javier on the swings.', '\"Hey guys,\" he said, but he didn\'t look that happy to see them.', 'Alex and Caleb sat in the swings on either side of him.', '\"Can you help us with our case?\" Alex asked.', '\"Um, okay,\" Javier said.', '\"How long can turtles live?\" asked Tully.', '\"Like 30 years sometimes\".', '\"Interesting.', 'So, it would be neat for your pet shop to have a rare turtle for sale, right?\" Javier cleared his throat nervously.', 'He glanced at Tully and then looked down at his hands.', '\"I guess so.', 'But it\'s my parents\' store, not mine.', 'We have a lot of other animals too, like lizards and gerbils and kittens and stuff\".', '\"What would you do with a million bucks?\" Rocket asked.', 'Javier blinked.', '\"Hmmm, I don\'t know.', 'Buy a zoo maybe? Why?\" \"Just wondering,\" Tully said.', 'She wrote down a few notes in her notebook.', 'Suspect: Javier.', 'Motive: profit from sale of Coco and her adorable baby turtles.', 'Evidence: weird, nervous behavior, possibly because of guilty conscience.', '\"Javier, could you tell us everything you did yesterday from before lunch until you left extended day?\" Tully asked very seriously.', 'Javier\'s face crumpled.', '\"You think I took Coco?\" Tully felt a prick of sympathy.', 'But detectives must be tough to get the truth.', '\"Javier, we need the facts\".','Javier shook his head.', '\"I went to the same classes as you did.', 'You can ask Miss Flores.', 'I never asked for a hall pass.', 'After school, I walked to extended day with Alex.', 'I was with him the whole time\".', 'Alex nodded.', '\"That is true\".', '\"Well, we will check your alibi with Miss Flores\".', 'Tully said.', '\"So, can I go now?\" Javier folded and unfolded his hands in his lap.', 'He kicked at the dirt beneath his swing.', '\"If you didn\'t do it, then how come you\'re acting so strange?\" Tully narrowed her eyes at him.', 'Javier took a deep breath and then said all in a rush, \"I\'m not supposed to tell that Tully\'s mother came into Claws and Paws to buy Tully a pet for her birthday.', 'And I\'m not supposed to tell that I helped her and it\'s going to be a\u2013\" \"Whoa! Javier don\'t tell her\".', 'Lyra said holding up her hands.', 'Lyra pulled Tully away from Javier and started walking back inside.', '\"Thank you for your help!\" she called over her shoulder.', 'She whispered to Tully, \"New rule: no talking to Javier until after your birthday party, got it?\" Tully had to promise and pinky swear three times before Lyra let her go.', '\"What now?\" Caleb asked when they got back inside.', '\"I feel like we\'re grasping at the straw that broke the camel\'s back!\" \"Me too,\" Alex said.', '\"Is there anyone else who would want a turtle, like for a pet?\" Caleb asked.', 'Alex wrinkled his nose, which made his glasses almost slide off.', '\"Well, Emily already has a turtle, and so does Xavier.', 'Abby has a bunny.', 'Carys has that yellow talking parakeet she brought for show and tell last year.', 'I think everybody else has regular pets, like cats and dogs and Guinea pigs\".', '\"Wait, people have pigs for pets?\" Rocket asked incredulously.', 'Alex laughed.', '\"Well, I think that\'s possible.', 'But Guinea pigs are little furry rodents.', 'Kind of like hamsters\".', 'Thinking of hamsters made Tully think of fluffy Howard and his cute pink nose.', 'Which made her think of the library and Coco\'s empty aquarium.', 'She then smacked her own forehead.', '\"Guys! We\'ve been missing a critical piece of evidence\".', 'Tully had almost completely forgotten about the block of cheese with the bite marks in it, which had probably been left by the turtle snatcher.', 'And maybe they could use it to catch him! Just then the bell rang.', '\"I will make sure to bring the cheese tomorrow and we will use it to find Coco,\" Tully said.', 'They all said their goodbyes and headed home for the day.', 'Tully woke up on Friday morning and it was pouring rain outside.', 'The sky was so dark that Tully almost crawled back beneath her blankets because she was so cozy.', 'But she had too much to do, including solving the turtle snatcher case and bringing Coco home safely.', 'She got on the bus and headed to school.', 'When the bus dropped her off, she pulled her raincoat\'s hood over her head and dashed through the rain.', 'Mr Sleuth held the front door open for her.', 'Caleb was already waiting in the lobby, shaking out his wet hair.', '\"Come on,\" Tully said grabbing his hand.', '\"We have work to do\".', 'They gathered the gang and went to the auditorium.', 'The Gumshoe gang sat in a circle on the stage, hidden behind the blue stage curtain.', 'They passed around the hunk of cheese, examining the bite marks on it with Tully\'s magnifying glass.', '\"You can see the marks on the top and bottom teeth biting all the way through the cheese, except for right there, in the front!\" Lyra said, examining the evidence.','Tully leaped to her feet.', '\"You\'re a genius! Whoever took that bite of cheese is missing a front tooth!\" \"Hmm, Megan and Emily are both missing teeth,\" Alex said.', '\"But that doesn\'t make sense, because Megan has already been cleared and Emily already has a turtle.', 'Why would she steal one?\" Tully reasoned.', 'She sank back down.', '\"Well, we could still talk to Emily,\" Caleb said, patting Tully\'s shoulder.', '\"That is true, okay, let\'s go find her!\" Tully said leaping to her feet.', 'The bell rang and it was library time.', '\"Perfect! Emily should be heading to the library now.', 'Let\'s go rattle her feathers\".', 'The rain splashed the window panes, but the library was warm and bright and smelled wonderful like dusty old books.', 'The rest of the class had spread out among the rows of bookshelves, searching for books to check out.', '\"This is the best time to find Emily,\" Alex said quietly.', 'They checked each row until they saw her.', 'She was looking down at a book in her hand, standing in front of the same animal section that Tully searched through on Wednesday.', '\"Oh, Emily\" Tully whispered.', 'Emily snapped the book shut and held it behind her back.', '\"Hey guys,\" she said.', '\"Can we talk to you?\" Alex asked.', 'Emily looked around, \"Um, sure\".', '\"We\'re looking for the turtle snatcher,\" Tully said, explaining about the cheese they found at the crime scene.', '\"Whoever bit the cheese is missing a tooth, and so are you\".', '\"But that could be lots of people,\" Emily said.', '\"Not as many as you might expect,\" said Alex.', '\"It\'s important that we find Coco,\" Tully said.', '\"She\'s pregnant and needs a safe place to lay her eggs\".', 'Emily\'s face went a little white.', '\"Really?\" she squeaked.', '\"I thought Coco was a boy\".', '\"Nope! Surprise!\" Caleb said.', '\"Well, I don\'t think I can help you.', 'Sorry!\" Emily said trying to walk away.', 'Tully was getting one of those funny detective feelings in her belly.', '\"Emily, maybe you can help us.', 'Can we see the book you were looking at?\" she asked.', 'Emily hesitated, biting her lower lip.', '\"Okay.', 'It\'s just, you know, a turtle book, because I have a turtle already.', 'As a pet, at home\".', 'She handed Tully the book: The Care and Feeding of Aquatic Turtles.', 'Tully stared at the cover.','\"Emily, Isn\'t your turtle a box turtle?\" Tully asked.', '\"Yes\".', '\"Box turtles are land turtles, right?\" \"Yes,\" Emily said so softly that they could barely hear her.', '\"But this book is for taking care of an aquatic turtle\u2013 a water turtle.', 'Coco is an aquatic turtle, right?\" Emily nodded.', 'Her lower lip was trembling.', '\"Emily,\" Tully said gently.', '\"Is there something you want to tell us?\" Emily started to cry.', '\"I\'m sorry.', 'I took Coco.', 'It was me\".', '\"But why?\" Caleb asked.', 'Emily sniffed.', '\"Because my turtle ran away.', 'On Tuesday, I took Bubbles out to play in my backyard, so he could have some fun in the sunshine.', 'I thought he was taking a nap so I went inside for a drink of water.', 'I guess turtles can move really fast when they want to, because when I came back outside, he was gone.', 'I looked everywhere.', 'I knew I\'d get in big trouble when my parents found out.', 'And I missed Bubbles so much.', 'I\'m very sorry.', 'I felt terrible this whole time\".', '\"When did you do it?\" Alex asked.', '\"When I heard Mr Hornswoggle was going to be away from the library all afternoon on Wednesday, I thought it was the answer to all of my troubles.', 'I sneaked away during lunch, taking my cheese stick with me to snack on.', 'I was putting Coco in my backpack when I heard a noise, so I crept behind one of the bookcases.', 'Megan came in to play with Howard.', 'As soon as she left, I ran right out of there.', 'And that\'s it.', 'Except Coco is acting funny.', 'He- I mean she -is not eating the food I\'m giving her.', 'She seems really unhappy.', 'And I just want Coco to be okay\".', 'Lyra put her arm around Emily\'s shoulder.', '\"It\'s okay, Emily.', 'We just need to bring Coco back to Mr Hornswoggle so she is safe\".', 'The Gumshoe gang went to find Mr Hornswoggle and explained everything.', 'He called Emily\'s parents, who said they\'d bring Coco back by the end of the school day.', 'He congratulated the Gumshoe gang on solving the case and thanked them for all of their hard work, especially Tully! \"I hope that I will see you tomorrow at my birthday party, Emily,\" Tully said as they were getting onto the bus.', '\"I can still come even though I stole Coco?\" she asked.', '\"Of course! Make sure to wear something elegant!\" Tully said and smiled at Emily.', 'It was finally the day of Tully\'s ninth birthday, and it was super fantastic.', 'She wore her silver and pink striped knee socks, a puffy orange skirt, a neon yellow shirt with a green glitter unicorn on it, and a pink feather boa wrapped around her neck.', 'All of her friends came, and guess what? It turned out that her birthday present from Mom was a giant glass aquarium with a note inside from Mr Hornswoggle.', 'It said: When Coco\'s hatchlings get big enough, Tully will have two Cagle\'s Map turtles for her very own.', 'Except she may have to share with me too! So that was the story of how my sister, the greatest detective in the world solved Watson Elementary\'s greatest mystery: The case of the turtle snatcher.'];

var defaults = [
    "DashedSentence", {mode: "self-paced reading", display: "in place"},
    "Form", {continueOnReturn: false, continueMessage: "Click here to continue with the story!"},
    "AY_Form", {continueOnReturn: true, continueMessage: null}, 
]; 
        
var items = [
    
["consent", "Form", {hideProgressBar: true, countsForProgressBar: false, continueMessage: null, continueOnReturn: true, consentRequired: true, html: {include: "LTEC_consent_2019.html" }} ],
["welcome", "AY_Form", {hideProgressBar: true, countsForProgressBar: false, consentRequired: true, continueMessage:"Click here to start", html: {include: "Welcome.html" }} ],
["demo", "Form", {hideProgressBar: true, countsForProgressBar: false, continueMessage: null, continueOnReturn: true, html: {include: "demographics.html" }} ],
["debrief", "Form", {hideProgressBar: true, countsForProgressBar: false, consentRequired: true, continueMessage:"Click here to continue", html: {include: "debrief_harvard.html" }} ],
["exit", "Form", {consentRequired: false, continueMessage:"Click here to continue", html: {include: "exit.html" }} ],
["setcounter", "__SetCounter__", { }],
["BookCover", "Message", {consentRequired: false, continueMessage:"Click here to begin!", html: {include: "BookCover.html" }} ],

    
// Coco Study: Norming all words from the story (word-by-word)
    
[["coco-Group1", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond1_Cloze_pt1.html"}},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "AY_Form", {html: {include: "cond1_Cloze_pt2.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(21, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}},
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}},
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}},
                     "DashedSentence", {s: fullStory.slice(226, 256)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],
    
[["coco-Group2", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 21)},  
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond2_Cloze_pt1.html"}},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "AY_Form", {html: {include: "cond2_Cloze_pt2.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(52, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}},
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}},
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}},
                     "DashedSentence", {s: fullStory.slice(226, 256)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],
    
 [["coco-Group3", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond3_Cloze_pt1.html"}},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}},
                     "AY_Form", {html: {include: "cond3_Cloze_pt2.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(72, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}},
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}},
                     "DashedSentence", {s: fullStory.slice(226, 256)},   
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],
    
 [["coco-Group4", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 72)},  
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond4_Cloze.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(92, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}},
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}},
                     "DashedSentence", {s: fullStory.slice(226, 256)},   
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],

[["coco-Group5", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 93)},  
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond5_Cloze.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(111, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}},
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}},
                     "DashedSentence", {s: fullStory.slice(226, 256)},   
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],  
    
[["coco-Group6", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 111)},  
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond6_Cloze.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(143, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}},
                     "DashedSentence", {s: fullStory.slice(153, 226)},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}},
                     "DashedSentence", {s: fullStory.slice(226, 256)},   
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}], 
    
[["coco-Group7", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 143)},  
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond7_Cloze_pt1.html"}},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}},
                     "AY_Form", {html: {include: "cond7_Cloze_pt2.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(172, 226)},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}},
                     "DashedSentence", {s: fullStory.slice(226, 256)},   
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],     
    
[["coco-Group8", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}}, 
                     "DashedSentence", {s: fullStory.slice(153, 172)},  
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond8_Cloze.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(198, 226)},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}},
                     "DashedSentence", {s: fullStory.slice(226, 256)},   
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],        
    
[["coco-Group9", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}}, 
                     "DashedSentence", {s: fullStory.slice(153, 198)},  
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond9_Cloze_pt1.html"}},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}},
                     "AY_Form", {html: {include: "cond9_Cloze_pt2.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(227, 256)},   
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],   
   
[["coco-Group10", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}}, 
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}}, 
                     "DashedSentence", {s: fullStory.slice(226, 227)},  
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond10_Cloze_pt1.html"}},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}},
                     "AY_Form", {html: {include: "cond10_Cloze_pt2.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(262, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],   
    
[["coco-Group11", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}}, 
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}}, 
                     "DashedSentence", {s: fullStory.slice(226, 256)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}}, 
                     "DashedSentence", {s: fullStory.slice(256, 262)},  
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond11_Cloze.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(289, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "DashedSentence", {s: fullStory.slice(309, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],   
  
  
[["coco-Group12", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}}, 
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}}, 
                     "DashedSentence", {s: fullStory.slice(226, 256)}, 
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}}, 
                     "DashedSentence", {s: fullStory.slice(256, 289)},   
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond12_Cloze_pt1.html"}},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}},
                     "AY_Form", {html: {include: "cond12_Cloze_pt2.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(311, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],    
  
[["coco-Group13", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}}, 
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}}, 
                     "DashedSentence", {s: fullStory.slice(226, 256)}, 
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}}, 
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}}, 
                     "DashedSentence", {s: fullStory.slice(309, 311)}, 
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond13_Cloze.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(342, 350)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "DashedSentence", {s: fullStory.slice(350, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}], 

[["coco-Group14", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}}, 
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}}, 
                     "DashedSentence", {s: fullStory.slice(226, 256)}, 
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}}, 
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}}, 
                     "DashedSentence", {s: fullStory.slice(309, 342)}, 
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond14_Cloze_pt1.html"}},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}},
                     "AY_Form", {html: {include: "cond14_Cloze_pt2.html"}},
                     "Message", {transfer: 4000, html: ["div", ["p", "Now, finish reading the story! You may see pictures during this section."], ["p", "Remember, use the 'Space' bar to continue."]]},
                     "DashedSentence", {s: fullStory.slice(376, 396)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}], 
    
[["coco-Group15", 1], "Message", {transfer: 4000, html: ["div", ["p", "You are about to start reading! You may see pictures during this section."], ["p", "Remember, push the 'Space' bar to make sentences appear! "]]},
                     "DashedSentence", {s: fullStory.slice(0, 6)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo1.html"}},
                     "DashedSentence", {s: fullStory.slice(6, 26)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo2.html"}},
                     "DashedSentence", {s: fullStory.slice(26, 55)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo3.html"}}, 
                     "DashedSentence", {s: fullStory.slice(55, 153)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo4.html"}}, 
                     "DashedSentence", {s: fullStory.slice(153, 226)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo5.html"}}, 
                     "DashedSentence", {s: fullStory.slice(226, 256)}, 
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo6.html"}}, 
                     "DashedSentence", {s: fullStory.slice(256, 309)},  
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo7.html"}}, 
                     "DashedSentence", {s: fullStory.slice(309, 350)}, 
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo8.html"}}, 
                     "DashedSentence", {s: fullStory.slice(350, 376)}, 
                     "Message", {transfer: 4000, html: ["div", ["p", "You are about to start guessing! You may see pictures during this section."], ["p", "After you finish guessing, you will read the rest of the story."]]},  
                     "AY_Form", {html: {include: "cond15_Cloze.html"}},
                     "Message", {transfer: 4100, continueOnReturn: false, html: {include: "photo9.html"}}],     
    
    
];

                        




